# Generated by Django 5.2.1 on 2025-12-21 22:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='School Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('users', models.ManyToManyField(blank=True, related_name='schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='DiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Discount Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Amount')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_configs', to='Quran.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Discount Config',
                'verbose_name_plural': 'Discount Configs',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Quran.school', verbose_name='School')),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='Quran.course', verbose_name='Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='Quran.school', verbose_name='School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must be exactly 14 digits.', regex='^\\d{14}$')], verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('code', models.CharField(blank=True, max_length=5, unique=True, verbose_name='Code')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('academic_year', models.CharField(choices=[('pre_primary', 'Pre-Primary'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('middle_1', 'Middle 1'), ('middle_2', 'Middle 2'), ('middle_3', 'Middle 3'), ('high_1', 'High 1'), ('high_2', 'High 2'), ('high_3', 'High 3'), ('university_1', 'University Year 1'), ('university_2', 'University Year 2'), ('university_3', 'University Year 3'), ('university_4', 'University Year 4'), ('graduate', 'Graduate')], max_length=20, null=True, verbose_name='Academic Year')),
                ('level', models.CharField(max_length=100, verbose_name='Level')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')], verbose_name='Phone Number')),
                ('parent_profession', models.CharField(max_length=100, verbose_name="Parent's profession")),
                ('discount_type', models.CharField(choices=[('none', 'No discount'), ('discount', 'Have discount'), ('full', 'Full discount')], default='none', max_length=10, verbose_name='Discount Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Quran.classgroup', verbose_name='Group')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Quran.school', verbose_name='School')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Month')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Year')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Amount')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Quran.school', verbose_name='School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='Quran.student', verbose_name='Student')),
            ],
            options={
                'unique_together': {('student', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must be exactly 14 digits.', regex='^\\d{14}$')], verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Teacher Name')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, verbose_name='Marital Status')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('qualification', models.CharField(max_length=100, verbose_name='Qualification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Quran.school', verbose_name='School')),
            ],
        ),
        migrations.AddField(
            model_name='classgroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='Quran.teacher', verbose_name='Teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('present', models.BooleanField(default=True, verbose_name='Present')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Quran.school', verbose_name='School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='Quran.student', verbose_name='Student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Month')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Quran.invoice', verbose_name='Invoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payment_statuses', to='Quran.school', verbose_name='School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_statuses', to='Quran.student', verbose_name='Student')),
            ],
            options={
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
