# Generated by Django 5.2.1 on 2025-11-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
