# Generated by Django 5.2.1 on 2025-12-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default=1, max_length=100, verbose_name='Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_profession',
            field=models.CharField(default=1, max_length=100, verbose_name="Parent's profession"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default=1, max_length=100, verbose_name='Qualification'),
            preserve_default=False,
        ),
    ]
