# Generated by Django 5.2.1 on 2025-11-15 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0002_rename_customuser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.RemoveField(
            model_name='group',
            name='school',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='school',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='Quran.course', verbose_name='Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='Quran.school', verbose_name='School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='Quran.teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Quran.classgroup', verbose_name='Group'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
