# Generated by Django 5.2.1 on 2025-12-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0002_student_level_student_parent_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], default=1, max_length=1, verbose_name='Marital Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(choices=[('pre_primary', 'Pre-Primary'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('middle_1', 'Middle 1'), ('middle_2', 'Middle 2'), ('middle_3', 'Middle 3'), ('high_1', 'High 1'), ('high_2', 'High 2'), ('high_3', 'High 3'), ('university_1', 'University Year 1'), ('university_2', 'University Year 2'), ('university_3', 'University Year 3'), ('university_4', 'University Year 4'), ('graduate', 'Graduate')], max_length=20, null=True, verbose_name='Academic Year'),
        ),
    ]
