# Generated by Django 5.2.1 on 2025-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0003_remove_group_course_remove_group_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No discount'), ('discount', 'Have discount'), ('full', 'Full discount')], default='none', max_length=10, verbose_name='Discount Type'),
        ),
    ]
