# Generated by Django 5.2.1 on 2025-11-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0005_attendance_updated_at_classgroup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(choices=[('pre_primary', 'Pre-Primary'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('middle_1', 'Middle 1'), ('middle_2', 'Middle 2'), ('middle_3', 'Middle 3'), ('high_1', 'High 1'), ('high_2', 'High 2'), ('high_3', 'High 3'), ('university_1', 'University Year 1'), ('university_2', 'University Year 2'), ('university_3', 'University Year 3'), ('university_4', 'University Year 4')], max_length=20, null=True, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Quran.classgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='Quran.school'),
        ),
    ]
