# Generated by Django 5.2.1 on 2025-11-29 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0006_teacher_description_alter_student_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Quran.school', verbose_name='School'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Discount Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Amount')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_configs', to='Quran.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Discount Config',
                'verbose_name_plural': 'Discount Configs',
            },
        ),
    ]
